#[macro_use]
pub mod op;

pub mod commands;
pub mod ui;

use clap::Parser;

#[derive(Parser, Debug)]
#[command(
    name = "jig",
    about = "Git worktree manager for parallel Claude Code sessions",
    version,
    after_help = "Use 'jig <command> --help' for more information about a command."
)]
pub struct Cli {
    /// Show verbose output (e.g. pruned repos at startup)
    #[arg(short = 'v', long = "verbose", global = true)]
    pub verbose: bool,

    /// Plain output: no colors, no decorations (for scripting)
    #[arg(long = "plain", global = true)]
    pub plain: bool,

    #[command(subcommand)]
    pub command: Option<Command>,
}

// Command enum generated by macro - doc comments come from Args structs
crate::command_enum! {
    #[command(visible_alias = "c")]
    (Create, commands::Create),

    #[command(visible_alias = "ls")]
    (List, commands::List),

    #[command(visible_alias = "o")]
    (Open, commands::Open),

    #[command(visible_alias = "rm")]
    (Remove, commands::Remove),

    (Commit, commands::Commit),
    (Issues, commands::Issues),
    (Exit, commands::Exit),
    (Config, commands::Config),
    (Spawn, commands::Spawn),
    (Pr, commands::Pr),
    (Ps, commands::Ps),
    (Attach, commands::Attach),
    (Resume, commands::Resume),
    (Notify, commands::Notify),
    (Kill, commands::Kill),
    (Nuke, commands::Nuke),
    (Init, commands::Init),
    (Update, commands::Update),
    (Version, commands::Version),
    (Which, commands::Which),
    (Health, commands::Health),
    (Daemon, commands::Daemon),

    #[command(visible_alias = "h")]
    (Home, commands::Home),

    (Hooks, commands::Hooks),
    #[command(name = "shell-init")]
    (ShellInit, commands::ShellInit),

    #[command(name = "shell-setup")]
    (ShellSetup, commands::ShellSetup),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::op::{LogSink, Op};

    fn sink(args: &[&str]) -> LogSink {
        Cli::parse_from(args)
            .command
            .expect("a subcommand")
            .log_sink()
    }

    #[test]
    fn only_watch_and_daemon_start_log_to_a_file() {
        assert_eq!(sink(&["jig", "ps", "-gw"]), LogSink::File);
        assert_eq!(sink(&["jig", "daemon", "start"]), LogSink::File);
    }

    #[test]
    fn everything_else_logs_to_stderr() {
        for args in [
            &["jig", "ps"][..],
            &["jig", "ps", "-g"],
            &["jig", "daemon"],
            &["jig", "daemon", "status"],
            &["jig", "daemon", "logs"],
            &["jig", "pr", "comments"],
            &["jig", "list"],
            &["jig", "version"],
        ] {
            assert_eq!(sink(args), LogSink::Stderr, "{args:?}");
        }
    }
}
