#[macro_use]
pub mod op;

pub mod commands;
pub mod ui;

use clap::Parser;

#[derive(Parser, Debug)]
#[command(
    name = "jig",
    about = "Git worktree manager for parallel Claude Code sessions",
    version,
    after_help = "Use 'jig <command> --help' for more information about a command."
)]
pub struct Cli {
    /// Show verbose output (e.g. pruned repos at startup)
    #[arg(short = 'v', long = "verbose", global = true)]
    pub verbose: bool,

    /// Plain output: no colors, no decorations (for scripting)
    #[arg(long = "plain", global = true)]
    pub plain: bool,

    #[command(subcommand)]
    pub command: Option<Command>,
}

// Command enum generated by macro - doc comments come from Args structs
crate::command_enum! {
    #[command(visible_alias = "c")]
    (Create, commands::Create),

    #[command(visible_alias = "ls")]
    (List, commands::List),

    #[command(visible_alias = "o")]
    (Open, commands::Open),

    #[command(visible_alias = "rm")]
    (Remove, commands::Remove),

    (Commit, commands::Commit),
    (Issues, commands::Issues),
    (Exit, commands::Exit),
    (Config, commands::Config),
    (Spawn, commands::Spawn),
    (Pr, commands::Pr),
    (Ps, commands::Ps),
    (Attach, commands::Attach),
    (Resume, commands::Resume),
    (Notify, commands::Notify),
    (Kill, commands::Kill),
    (Nuke, commands::Nuke),
    (Init, commands::Init),
    (Update, commands::Update),
    (Version, commands::Version),
    (Which, commands::Which),
    (Health, commands::Health),
    (Daemon, commands::Daemon),

    #[command(visible_alias = "h")]
    (Home, commands::Home),

    (Hooks, commands::Hooks),
    #[command(name = "shell-init")]
    (ShellInit, commands::ShellInit),

    #[command(name = "shell-setup")]
    (ShellSetup, commands::ShellSetup),
}

impl Command {
    /// Whether this invocation will run the daemon's tick loop.
    ///
    /// This decides which log file the process writes, and a `-daemon.log`
    /// is a claim `jig daemon logs` trusts later: it picks the newest one
    /// when no daemon is up to name its own. So only an invocation that
    /// really runs the loop may write one, or a client leaves an empty file
    /// that shadows the real daemon's log.
    pub fn runs_daemon_loop(&self) -> bool {
        self.runs_daemon_loop_with(crate::daemon::ipc::is_running)
    }

    /// `daemon_is_running` is injected so the decision is testable without a
    /// live socket.
    fn runs_daemon_loop_with(&self, daemon_is_running: impl Fn() -> bool) -> bool {
        match self {
            Command::Daemon(d) => matches!(d.command, Some(commands::daemon::Command::Start(_))),
            // `ps --watch` hosts a daemon only when none is already
            // listening — which the parsed arguments cannot tell us, so ask.
            // Against a running daemon it is a plain client.
            Command::Ps(ps) => ps.watch.is_some() && !daemon_is_running(),
            _ => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn command_from(args: &[&str]) -> Command {
        Cli::parse_from(args).command.expect("a subcommand")
    }

    #[test]
    fn daemon_start_runs_the_loop() {
        assert!(command_from(&["jig", "daemon", "start"]).runs_daemon_loop_with(|| false));
        // Even with one already up: `start` refuses later, but while it runs
        // it is the daemon, not a client.
        assert!(command_from(&["jig", "daemon", "start"]).runs_daemon_loop_with(|| true));
    }

    #[test]
    fn other_daemon_subcommands_do_not() {
        for args in [
            vec!["jig", "daemon", "status"],
            vec!["jig", "daemon", "stop"],
            vec!["jig", "daemon", "logs"],
            vec!["jig", "daemon"],
        ] {
            assert!(
                !command_from(&args).runs_daemon_loop_with(|| false),
                "{args:?} should not claim the daemon log"
            );
        }
    }

    #[test]
    fn watch_hosts_only_when_no_daemon_is_listening() {
        let watch = command_from(&["jig", "ps", "-gw"]);
        assert!(
            watch.runs_daemon_loop_with(|| false),
            "with no daemon up, `ps --watch` hosts one"
        );
        assert!(
            !watch.runs_daemon_loop_with(|| true),
            "against a running daemon, `ps --watch` is a client and must not \
             write a -daemon.log that shadows the real one"
        );
    }

    #[test]
    fn plain_ps_never_runs_the_loop() {
        // A one-shot tick is not the daemon loop, and leaves no daemon log.
        assert!(!command_from(&["jig", "ps"]).runs_daemon_loop_with(|| false));
        assert!(!command_from(&["jig", "ps", "-g"]).runs_daemon_loop_with(|| false));
    }

    #[test]
    fn unrelated_commands_never_run_the_loop() {
        assert!(!command_from(&["jig", "list"]).runs_daemon_loop_with(|| false));
        assert!(!command_from(&["jig", "version"]).runs_daemon_loop_with(|| true));
    }
}
