#[macro_use]
pub mod op;

pub mod commands;
pub mod ui;

use clap::Parser;

#[derive(Parser, Debug)]
#[command(
    name = "jig",
    about = "Git worktree manager for parallel Claude Code sessions",
    version,
    after_help = "Use 'jig <command> --help' for more information about a command."
)]
pub struct Cli {
    /// Show verbose output (e.g. pruned repos at startup)
    #[arg(short = 'v', long = "verbose", global = true)]
    pub verbose: bool,

    /// Plain output: no colors, no decorations (for scripting)
    #[arg(long = "plain", global = true)]
    pub plain: bool,

    #[command(subcommand)]
    pub command: Option<Command>,
}

// Command enum generated by macro - doc comments come from Args structs
crate::command_enum! {
    #[command(visible_alias = "c")]
    (Create, commands::Create),

    #[command(visible_alias = "ls")]
    (List, commands::List),

    #[command(visible_alias = "o")]
    (Open, commands::Open),

    #[command(visible_alias = "rm")]
    (Remove, commands::Remove),

    (Commit, commands::Commit),
    (Issues, commands::Issues),
    (Exit, commands::Exit),
    (Config, commands::Config),
    (Spawn, commands::Spawn),
    (Pr, commands::Pr),
    (Ps, commands::Ps),
    (Attach, commands::Attach),
    (Resume, commands::Resume),
    (Notify, commands::Notify),
    (Kill, commands::Kill),
    (Nuke, commands::Nuke),
    (Init, commands::Init),
    (Update, commands::Update),
    (Version, commands::Version),
    (Which, commands::Which),
    (Health, commands::Health),

    #[command(visible_alias = "h")]
    (Home, commands::Home),

    (Hooks, commands::Hooks),
    #[command(name = "shell-init")]
    (ShellInit, commands::ShellInit),

    #[command(name = "shell-setup")]
    (ShellSetup, commands::ShellSetup),
}
